# Home routes
app_home:
    path: /
    controller: App\Controller\HomeController::index

about:
    path: /about
    controller: App\Controller\HomeController::about

stats:
    path: /stats
    controller: App\Controller\HomeController::stats

random_books:
    path: /random-books
    controller: App\Controller\HomeController::randomBooks

word_of_day:
    path: /word-of-day
    controller: App\Controller\HomeController::wordOfTheDay

quote_of_day:
    path: /quote-of-day
    controller: App\Controller\HomeController::quoteOfTheDay

# Books routes
books_dashboard:
    path: /books
    controller: App\Controller\BookController::dashboard

books_search:
    path: /books/search
    controller: App\Controller\BookController::search
    methods: [GET]

books_latest:
    path: /books/latest
    controller: App\Controller\BookController::latest

books_random:
    path: /books/random/{count}
    controller: App\Controller\BookController::random
    defaults:
        count: 1
    requirements:
        count: '\d+'

books_recent:
    path: /books/recent
    controller: App\Controller\BookController::recent



books_forgotten:
    path: /books/forgotten
    controller: App\Controller\BookController::forgotten

books_visit_records:
    path: /books/visit-records
    controller: App\Controller\BookController::visitRecords

books_lucky:
    path: /books/lucky
    controller: App\Controller\BookController::lucky

books_list:
    path: /books/list/{key}/{value}/{page}
    controller: App\Controller\BookController::listFiltered
    defaults:
        key: 'title'
        value: '-'
        page: 1
    requirements:
        page: '\d+'

book_details:
    path: /books/{bookId}.html
    controller: App\Controller\BookController::details
    requirements:
        bookId: '.+'

# API routes
api_add_tags:
    path: /api/books/{bookId}/tags
    controller: App\Controller\ApiController::addTagsToBook
    methods: [POST]
    requirements:
        bookId: '.+'

books_today:
    path: /books/today
    controller: App\Controller\BookController::todaysBooks
    methods: [GET]

# Turbo frame routes
book_tags_frame:
    path: /books/{bookId}/tags-frame
    controller: App\Controller\BookController::bookTags
    requirements:
        bookId: '.+'
