# Home routes
app_home:
    path: /
    controller: App\Controller\HomeController::index

about:
    path: /about
    controller: App\Controller\HomeController::about

stats:
    path: /stats
    controller: App\Controller\HomeController::stats

random_books:
    path: /random-books
    controller: App\Controller\HomeController::randomBooks

# Books routes
books_dashboard:
    path: /books
    controller: App\Controller\BookController::dashboard

books_search:
    path: /books/search
    controller: App\Controller\BookController::search
    methods: [GET]

books_latest:
    path: /books/latest
    controller: App\Controller\BookController::latest

books_random:
    path: /books/random
    controller: App\Controller\BookController::random

books_recent:
    path: /books/recent
    controller: App\Controller\BookController::recent

books_forgotten:
    path: /books/forgotten
    controller: App\Controller\BookController::forgotten

books_today:
    path: /books/today/{month}/{date}
    controller: App\Controller\BookController::today
    requirements:
        month: '\d+'
        date: '\d+'

books_list:
    path: /books/list/{key}/{value}/{page}
    controller: App\Controller\BookController::listFiltered
    defaults:
        key: 'title'
        value: '-'
        page: 1
    requirements:
        page: '\d+'

book_details:
    path: /books/{bookId}.html
    controller: App\Controller\BookController::details
    requirements:
        bookId: '.+'

# API routes
api_add_tags:
    path: /api/books/{bookId}/tags
    controller: App\Controller\ApiController::addTagsToBook
    methods: [POST]
    requirements:
        bookId: '.+'

# Turbo frame routes
book_tags_frame:
    path: /books/{bookId}/tags-frame
    controller: App\Controller\BookController::bookTags
    requirements:
        bookId: '.+'
